baseURL = "/"
languageCode = "en-us"

title = "Euskara ikasteko baliabideak"
# Change the default theme to be use when building the site with Hugo
#theme = "hugo-theme-learn"
metaDataFormat = "toml"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]
#baseName="index"
#mediaType = "text/html
#isHTML = true
